export type TypeIconName = 'bag-fill' |
'exclamation-square' |
'arrow-up-circle' |
'file-post-fill' |
'cloud-fog-fill' |
'wrench-adjustable-circle-fill' |
'house-door' |
'record-circle-fill' |
'filetype-md' |
'calendar-month' |
'calendar2-fill' |
'explicit' |
'person-plus-fill' |
'lightbulb-off-fill' |
'diagram-3-fill' |
'info' |
'tags' |
'dot' |
'exclamation-diamond' |
'music-note-list' |
'file-earmark-arrow-up-fill' |
'calendar-plus-fill' |
'pentagon-fill' |
'arrow-bar-right' |
'activity' |
'shuffle' |
'heart-pulse-fill' |
'broadcast-pin' |
'list-stars' |
'collection-play' |
'truck' |
'filetype-jsx' |
'code-slash' |
'clock-history' |
'skip-forward-fill' |
'file-font-fill' |
'table' |
'cloud-arrow-down-fill' |
'heart-arrow' |
'skip-end-btn-fill' |
'hdd-stack-fill' |
'folder-minus' |
'file-earmark-zip' |
'list-ol' |
'file-earmark-pdf-fill' |
'file-arrow-down-fill' |
'person-heart' |
'easel3' |
'lightbulb-fill' |
'play' |
'map-fill' |
'node-plus-fill' |
'file-lock-fill' |
'skip-forward-circle-fill' |
'arrow-clockwise' |
'filetype-php' |
'receipt-cutoff' |
'trash2-fill' |
'person-circle' |
'box-seam' |
'easel2' |
'file-arrow-up' |
'file-bar-graph-fill' |
'envelope-check' |
'badge-hd-fill' |
'bag-check-fill' |
'chevron-left' |
'nut-fill' |
'usb-mini' |
'ui-checks-grid' |
'clipboard2-heart-fill' |
'bookmark-fill' |
'arrow-right-circle' |
'bookmark' |
'border-inner' |
'journal-bookmark' |
'mouse3-fill' |
'braces' |
'envelope-fill' |
'gear' |
'ticket-detailed' |
'person-hearts' |
'skip-start-btn-fill' |
'graph-down' |
'dash-circle' |
'backspace-fill' |
'envelope-exclamation-fill' |
'award-fill' |
'file-earmark-diff' |
'send' |
'usb-symbol' |
'mailbox2' |
'funnel' |
'clock-fill' |
'camera-fill' |
'display' |
'tags-fill' |
'sunset' |
'hypnotize' |
'usb-c' |
'modem-fill' |
'filetype-txt' |
'camera-video-off-fill' |
'chat-square-text' |
'gender-female' |
'door-closed' |
'heart-fill' |
'card-checklist' |
'cloud-arrow-up-fill' |
'peace-fill' |
'envelope-heart-fill' |
'exclamation-square-fill' |
'headset-vr' |
'exclamation' |
'calendar4-range' |
'calendar-month-fill' |
'info-square' |
'skip-backward-circle-fill' |
'box-arrow-in-down' |
'window-x' |
'filetype-js' |
'caret-down' |
'sort-numeric-up' |
'tiktok' |
'cloud-lightning-rain' |
'filter-circle-fill' |
'file-earmark-arrow-up' |
'file-earmark-lock2-fill' |
'broadcast' |
'skip-forward' |
'upc' |
'suit-heart-fill' |
'gem' |
'suit-heart' |
'bag-plus-fill' |
'justify' |
'envelope-open-heart' |
'clipboard-heart' |
'file-slides-fill' |
'fan' |
'clipboard-plus' |
'binoculars' |
'spotify' |
'hourglass-split' |
'x-circle-fill' |
'plus-circle-fill' |
'qr-code-scan' |
'layout-three-columns' |
'send-plus' |
'file-check-fill' |
'file-ppt' |
'file-richtext' |
'door-open' |
'brightness-low' |
'file-earmark-word' |
'ear-fill' |
'slash-lg' |
'suit-spade' |
'snow2' |
'hdd-network-fill' |
'clipboard-x' |
'skip-forward-btn' |
'kanban' |
'cup-straw' |
'eyeglasses' |
'check-square-fill' |
'envelope-plus-fill' |
'shield-fill-plus' |
'book-fill' |
'filetype-otf' |
'search-heart' |
'x-circle' |
'boombox' |
'cart-dash' |
'send-slash-fill' |
'window-desktop' |
'compass-fill' |
'basket3-fill' |
'grid-3x3' |
'ticket' |
'arrow-bar-up' |
'heart-pulse' |
'arrow-bar-down' |
'wordpress' |
'node-plus' |
'search-heart-fill' |
'battery-full' |
'file-code-fill' |
'caret-right-square-fill' |
'credit-card' |
'telephone-plus' |
'shield' |
'window-dock' |
'file-lock2-fill' |
'file-earmark-ruled' |
'person-lines-fill' |
'arrow-left-short' |
'chat-square-text-fill' |
'check2-all' |
'file-x-fill' |
'envelope-x-fill' |
'vr' |
'arrow-down-up' |
'grip-horizontal' |
'box-arrow-down-left' |
'chevron-double-up' |
'signpost-split-fill' |
'ui-radios' |
'file-lock2' |
'bell' |
'sort-down' |
'distribute-vertical' |
'box-arrow-down-right' |
'markdown-fill' |
'clipboard-check-fill' |
'info-circle-fill' |
'arrow-down-right-square' |
'chat-heart' |
'pause' |
'chat-left-text' |
'lightning-fill' |
'filetype-psd' |
'segmented-nav' |
'hexagon' |
'rss-fill' |
'files-alt' |
'patch-plus-fill' |
'union' |
'dice-3' |
'cloud-download' |
'x' |
'arrow-down-right-circle' |
'terminal-dash' |
'sunset-fill' |
'telephone-inbound-fill' |
'caret-right-square' |
'pc-display' |
'palette' |
'octagon-fill' |
'skip-backward-btn' |
'phone-landscape-fill' |
'chat-square-dots-fill' |
'calendar-event-fill' |
'cloud-drizzle-fill' |
'arrow-down-circle' |
'messenger' |
'currency-pound' |
'journal' |
'text-indent-right' |
'menu-down' |
'pie-chart-fill' |
'emoji-smile-upside-down' |
'emoji-dizzy' |
'caret-down-square' |
'arrow-90deg-up' |
'file-earmark-text-fill' |
'eye-slash' |
'calendar2-range' |
'box-arrow-in-left' |
'markdown' |
'chat-heart-fill' |
'journal-medical' |
'journal-code' |
'clipboard2-pulse' |
'file-spreadsheet' |
'check2-circle' |
'telephone-fill' |
'arrow-right-square-fill' |
'bag-dash-fill' |
'filetype-key' |
'behance' |
'easel-fill' |
'badge-wc-fill' |
'calendar-day-fill' |
'patch-check-fill' |
'terminal-fill' |
'file-minus-fill' |
'strava' |
'x-diamond-fill' |
'flag' |
'symmetry-horizontal' |
'clipboard2-x' |
'cloud-arrow-up' |
'grid' |
'lightbulb' |
'node-minus-fill' |
'command' |
'currency-dollar' |
'laptop' |
'hand-index-thumb' |
'file-person-fill' |
'hdmi-fill' |
'type-underline' |
'cast' |
'pencil' |
'speaker-fill' |
'tsunami' |
'shield-x' |
'life-preserver' |
'badge-ad-fill' |
'calendar-minus' |
'compass' |
'file-check' |
'play-fill' |
'collection' |
'border-left' |
'chevron-bar-contract' |
'signpost-2' |
'camera-reels' |
'cpu' |
'sort-up' |
'bank2' |
'balloon' |
'triangle' |
'tornado' |
'emoji-sunglasses' |
'file-earmark' |
'box-arrow-in-up' |
'hdd-stack' |
'geo-alt' |
'eye' |
'shield-shaded' |
'kanban-fill' |
'wifi-2' |
'calendar-date' |
'trophy-fill' |
'star-fill' |
'envelope-plus' |
'file-pdf-fill' |
'eye-fill' |
'hdd' |
'chat-left-heart' |
'sd-card' |
'volume-off' |
'calendar-week-fill' |
'inbox-fill' |
'file-earmark-zip-fill' |
'file-minus' |
'chevron-bar-expand' |
'moon-stars' |
'play-btn-fill' |
'file-slides' |
'bookmark-star-fill' |
'rainbow' |
'arrow-down-square' |
'badge-ad' |
'send-exclamation-fill' |
'emoji-heart-eyes' |
'badge-tm-fill' |
'calculator' |
'plus-square-fill' |
'droplet-half' |
'chevron-bar-down' |
'emoji-heart-eyes-fill' |
'award' |
'bar-chart-line-fill' |
'telephone-minus' |
'wrench-adjustable-circle' |
'postage-fill' |
'menu-button-wide-fill' |
'cloud-sleet' |
'calendar2-check' |
'list-nested' |
'file-bar-graph' |
'mailbox' |
'shield-slash-fill' |
'reply-all-fill' |
'bookshelf' |
'inboxes' |
'patch-minus' |
'bookmark-check' |
'envelope-exclamation' |
'exclamation-circle-fill' |
'apple' |
'skype' |
'diamond-half' |
'pentagon' |
'volume-up' |
'peace' |
'send-dash-fill' |
'emoji-frown' |
'border-top' |
'emoji-wink-fill' |
'globe' |
'hand-thumbs-down-fill' |
'bookmark-heart-fill' |
'capslock' |
'bezier2' |
'calendar3-week' |
'columns' |
'info-lg' |
'toggle-on' |
'house-heart' |
'earbuds' |
'square-half' |
'sticky' |
'arrow-right' |
'123' |
'filter-right' |
'battery-charging' |
'filetype-tiff' |
'calendar2-heart' |
'boxes' |
'heart-half' |
'person-plus' |
'layout-split' |
'calendar4-week' |
'patch-check' |
'x-octagon-fill' |
'filetype-m4p' |
'file-earmark-binary' |
'subtract' |
'reception-1' |
'cloud-lightning-rain-fill' |
'key' |
'view-list' |
'arrow-right-short' |
'calculator-fill' |
'calendar-event' |
'outlet' |
'mortarboard-fill' |
'flower2' |
'record-btn-fill' |
'calendar-heart-fill' |
'file-earmark-person-fill' |
'pause-circle-fill' |
'file-music-fill' |
'explicit-fill' |
'send-check-fill' |
'eject' |
'device-ssd' |
'wallet' |
'stopwatch-fill' |
'text-center' |
'arrows-fullscreen' |
'postage-heart-fill' |
'save2-fill' |
'clipboard-plus-fill' |
'quote' |
'tropical-storm' |
'node-minus' |
'question-octagon' |
'arrow-down-left-circle-fill' |
'hospital' |
'piggy-bank-fill' |
'arrow-90deg-left' |
'folder-check' |
'play-circle-fill' |
'hospital-fill' |
'heart' |
'chat-right' |
'projector' |
'calendar-check-fill' |
'discord' |
'cart-x' |
'filetype-ppt' |
'microsoft' |
'filetype-doc' |
'hand-index-fill' |
'octagon' |
'skip-start-circle' |
'trash-fill' |
'clipboard2-minus-fill' |
'file-earmark-ruled-fill' |
'arrow-up-left-circle-fill' |
'tv' |
'chat-left-heart-fill' |
'bell-slash-fill' |
'skip-end-btn' |
'align-end' |
'calendar2-week' |
'file-earmark-minus-fill' |
'chevron-double-down' |
'bucket-fill' |
'line' |
'geo-alt-fill' |
'cloud-moon-fill' |
'file-earmark-minus' |
'trash3' |
'bag-x-fill' |
'printer-fill' |
'stickies' |
'reply-fill' |
'cash-coin' |
'file-earmark-font-fill' |
'border-bottom' |
'filetype-heic' |
'pc-horizontal' |
'heptagon-fill' |
'chat-text-fill' |
'layout-sidebar-reverse' |
'bookmark-star' |
'thermometer-half' |
'basket3' |
'patch-question' |
'reddit' |
'grid-3x3-gap' |
'postage' |
'cloud-haze-fill' |
'arrow-left' |
'currency-exchange' |
'card-heading' |
'toggles' |
'unlock-fill' |
'backspace-reverse' |
'border-right' |
'snapchat' |
'ethernet' |
'calendar2-check-fill' |
'chat-left-dots' |
'file-earmark-check' |
'inboxes-fill' |
'usb-c-fill' |
'archive' |
'cloud-rain' |
'phone-vibrate-fill' |
'person-x' |
'arrow-up-short' |
'question' |
'terminal-plus' |
'border-width' |
'briefcase-fill' |
'chat-square-dots' |
'forward-fill' |
'app-indicator' |
'house' |
'dash-circle-dotted' |
'box-arrow-up-left' |
'chat-left-text-fill' |
'box' |
'reception-2' |
'hourglass-top' |
'file-diff' |
'clipboard-minus-fill' |
'folder-symlink' |
'display-fill' |
'filetype-aac' |
'exclamation-triangle-fill' |
'file-ruled-fill' |
'hdd-rack' |
'file-word-fill' |
'people-fill' |
'filetype-gif' |
'bookmark-dash-fill' |
'tree' |
'infinity' |
'minecart' |
'star' |
'pause-circle' |
'mastodon' |
'emoji-angry-fill' |
'plugin' |
'bookmarks-fill' |
'images' |
'hdd-fill' |
'git' |
'tablet-landscape-fill' |
'journal-plus' |
'badge-4k-fill' |
'badge-3d' |
'hdd-rack-fill' |
'server' |
'arrow-up-right' |
'envelope-dash-fill' |
'cloud-slash-fill' |
'hexagon-fill' |
'filetype-mp3' |
'person-dash' |
'headphones' |
'coin' |
'send-plus-fill' |
'credit-card-2-front-fill' |
'question-lg' |
'bookmark-plus-fill' |
'file-earmark-excel' |
'filetype-bmp' |
'pin-map-fill' |
'skip-backward-circle' |
'xbox' |
'filetype-scss' |
'chevron-compact-down' |
'chat-left' |
'exclamation-triangle' |
'filetype-png' |
'file-earmark-slides-fill' |
'reception-0' |
'forward' |
'plus' |
'intersect' |
'cone-striped' |
'calendar2-heart-fill' |
'arrows-expand' |
'patch-plus' |
'file-post' |
'bounding-box-circles' |
'person-badge' |
'clipboard2-data-fill' |
'list-ul' |
'layout-sidebar-inset-reverse' |
'chevron-bar-right' |
'controller' |
'window' |
'filetype-rb' |
'chat-left-quote' |
'envelope-dash' |
'filetype-py' |
'calendar-x-fill' |
'eject-fill' |
'layer-forward' |
'brightness-alt-high' |
'file-earmark-music' |
'cloud-check-fill' |
'dpad-fill' |
'mouse' |
'ticket-perforated-fill' |
'diagram-3' |
'volume-down-fill' |
'sun-fill' |
'calendar-check' |
'telephone-x' |
'file-medical' |
'file-earmark-pdf' |
'box-arrow-up-right' |
'cloud-moon' |
'brightness-alt-low' |
'arrow-down-circle-fill' |
'binoculars-fill' |
'download' |
'badge-ar' |
'chat-right-text-fill' |
'badge-8k-fill' |
'shield-minus' |
'file-earmark-x' |
'emoji-expressionless-fill' |
'bug-fill' |
'envelope-slash' |
'joystick' |
'bell-slash' |
'reception-3' |
'slash' |
'chat-dots' |
'send-x-fill' |
'shift-fill' |
'arrow-left-square' |
'textarea-resize' |
'sort-alpha-up-alt' |
'chat-right-text' |
'type-h2' |
'tools' |
'question-diamond' |
'ticket-perforated' |
'file-earmark-image' |
'umbrella-fill' |
'dash-lg' |
'bounding-box' |
'windows' |
'cpu-fill' |
'files' |
'cart-fill' |
'person-rolodex' |
'stickies-fill' |
'file-earmark-diff-fill' |
'caret-up-fill' |
'bag-dash' |
'mic' |
'calendar3-event-fill' |
'tree-fill' |
'youtube' |
'check-lg' |
'info-square-fill' |
'filetype-xls' |
'file-binary-fill' |
'record-circle' |
'bricks' |
'radioactive' |
'file-earmark-spreadsheet' |
'keyboard-fill' |
'brightness-low-fill' |
'shield-lock' |
'dash-square-fill' |
'cup-fill' |
'x-diamond' |
'suit-club' |
'journal-richtext' |
'slack' |
'stop-fill' |
'file-earmark-ppt' |
'pause-btn' |
'file-spreadsheet-fill' |
'postage-heart' |
'thermometer-high' |
'hurricane' |
'alt' |
'paperclip' |
'filetype-css' |
'clipboard2-data' |
'voicemail' |
'file-earmark-medical' |
'pie-chart' |
'collection-play-fill' |
'file-earmark-fill' |
'cloud-hail-fill' |
'file-arrow-up-fill' |
'usb' |
'displayport-fill' |
'file-earmark-code' |
'hexagon-half' |
'backspace-reverse-fill' |
'x-square-fill' |
'lightning' |
'cloud-lightning-fill' |
'x-lg' |
'bookmarks' |
'reply' |
'bandaid-fill' |
'camera-video' |
'smartwatch' |
'usb-drive' |
'suit-diamond-fill' |
'bag-check' |
'sort-up-alt' |
'bootstrap-reboot' |
'arrows-collapse' |
'arrow-left-circle' |
'brush-fill' |
'postcard-fill' |
'shield-exclamation' |
'chevron-double-right' |
'sun' |
'slash-circle' |
'card-list' |
'align-center' |
'emoji-sunglasses-fill' |
'journal-minus' |
'terminal-x' |
'file-break-fill' |
'currency-yen' |
'pin-fill' |
'arrow-down-right' |
'grip-vertical' |
'thermometer-low' |
'chat-square-quote-fill' |
'circle-fill' |
'power' |
'arrow-down-left-square' |
'toggle-off' |
'clipboard2' |
'moon-stars-fill' |
'person-workspace' |
'file-earmark-plus-fill' |
'motherboard' |
'bar-chart-line' |
'pc-display-horizontal' |
'easel' |
'filetype-yml' |
'receipt' |
'pencil-fill' |
'pin-map' |
'emoji-smile' |
'menu-app' |
'chat-text' |
'file-pdf' |
'valentine' |
'arrow-left-circle-fill' |
'align-top' |
'layout-wtf' |
'cloud-slash' |
'dice-4-fill' |
'cursor' |
'emoji-smile-fill' |
'send-fill' |
'calendar2-date' |
'fingerprint' |
'arrow-up-right-circle-fill' |
'plus-square' |
'caret-left-square-fill' |
'shield-fill-x' |
'view-stacked' |
'badge-vr' |
'plus-lg' |
'suit-diamond' |
'droplet' |
'camera' |
'calendar-heart' |
'gear-fill' |
'border-middle' |
'app' |
'calendar-x' |
'archive-fill' |
'skip-backward' |
'clipboard2-plus-fill' |
'file-earmark-lock2' |
'file-word' |
'mic-fill' |
'bezier' |
'pin-angle-fill' |
'safe2' |
'lightbulb-off' |
'file-earmark-binary-fill' |
'record-btn' |
'align-middle' |
'check-circle-fill' |
'stop' |
'sort-alpha-up' |
'usb-fill' |
'box-arrow-down' |
'arrow-return-right' |
'chat-left-quote-fill' |
'volume-mute' |
'badge-3d-fill' |
'plug' |
'record' |
'puzzle-fill' |
'brightness-high-fill' |
'medium' |
'skip-start-fill' |
'send-dash' |
'skip-end' |
'pause-fill' |
'soundwave' |
'shield-plus' |
'postcard-heart-fill' |
'chat-right-quote' |
'brightness-high' |
'nut' |
'calendar3-range-fill' |
'filetype-ai' |
'telephone-forward-fill' |
'menu-button-fill' |
'plug-fill' |
'box2-heart' |
'mic-mute-fill' |
'alarm-fill' |
'webcam-fill' |
'cloud-check' |
'shop' |
'graph-up' |
'arrow-down-left-square-fill' |
'brightness-alt-low-fill' |
'window-stack' |
'filetype-jpg' |
'filetype-raw' |
'file-earmark-arrow-down' |
'paypal' |
'slash-square' |
'cloud-fog' |
'chevron-compact-right' |
'envelope-paper-heart-fill' |
'filetype-sh' |
'image-fill' |
'lock-fill' |
'file-earmark-x-fill' |
'ui-checks' |
'hdmi' |
'volume-down' |
'collection-fill' |
'clipboard2-heart' |
'shield-fill-minus' |
'grid-1x2' |
'file-earmark-bar-graph-fill' |
'journal-album' |
'heartbreak' |
'eraser-fill' |
'sliders2' |
'map' |
'emoji-neutral' |
'volume-mute-fill' |
'bullseye' |
'house-heart-fill' |
'lightning-charge' |
'emoji-neutral-fill' |
'moon-fill' |
'arrow-up-right-circle' |
'cloud-plus-fill' |
'wifi-1' |
'filetype-mov' |
'menu-up' |
'shield-fill-check' |
'flower3' |
'sort-alpha-down-alt' |
'chat-square-heart-fill' |
'filetype-pptx' |
'skip-start-btn' |
'eyedropper' |
'type-bold' |
'slash-square-fill' |
'calendar2-minus-fill' |
'file-earmark-medical-fill' |
'person-fill' |
'clipboard2-minus' |
'filetype-pdf' |
'list' |
'paragraph' |
'balloon-fill' |
'file-earmark-image-fill' |
'dice-6' |
'heartbreak-fill' |
'backspace' |
'vimeo' |
'clipboard-data' |
'diagram-2-fill' |
'file-ruled' |
'wallet2' |
'input-cursor' |
'funnel-fill' |
'speaker' |
'envelope-paper' |
'telephone-x-fill' |
'sunrise' |
'house-door-fill' |
'patch-question-fill' |
'check-square' |
'clouds' |
'film' |
'optical-audio-fill' |
'cloud-fog2' |
'door-open-fill' |
'pin-angle' |
'save-fill' |
'bar-chart' |
'skip-start-circle-fill' |
'dash-square-dotted' |
'usb-micro' |
'cloud-haze' |
'facebook' |
'cart2' |
'chevron-contract' |
'stop-circle-fill' |
'camera-video-off' |
'pci-card' |
'clipboard-pulse' |
'boombox-fill' |
'border-center' |
'arrow-through-heart' |
'text-indent-left' |
'file' |
'bluetooth' |
'stars' |
'cart-x-fill' |
'egg-fill' |
'pip-fill' |
'calendar-day' |
'box-arrow-up' |
'clouds-fill' |
'arrow-right-circle-fill' |
'eye-slash-fill' |
'clipboard2-x-fill' |
'person-badge-fill' |
'safe' |
'gear-wide-connected' |
'filetype-xml' |
'toggle2-on' |
'calendar3-range' |
'file-text' |
'calendar2-minus' |
'wallet-fill' |
'record2-fill' |
'person-dash-fill' |
'at' |
'linkedin' |
'easel2-fill' |
'building' |
'gender-trans' |
'droplet-fill' |
'arrow-down-left' |
'trash' |
'chat-right-dots-fill' |
'phone-flip' |
'cart3' |
'card-image' |
'dice-1-fill' |
'hash' |
'dribbble' |
'hand-thumbs-up' |
'slash-circle-fill' |
'filetype-tsx' |
'cart-dash-fill' |
'layout-sidebar-inset' |
'gender-male' |
'trash2' |
'bell-fill' |
'emoji-laughing' |
'palette-fill' |
'align-start' |
'filetype-json' |
'window-split' |
'emoji-dizzy-fill' |
'envelope-heart' |
'calendar-week' |
'pencil-square' |
'dice-5-fill' |
'chevron-right' |
'ticket-fill' |
'hammer' |
'file-image' |
'gift' |
'clipboard-minus' |
'back' |
'megaphone' |
'info-circle' |
'calendar4' |
'thermometer-sun' |
'chat-square-heart' |
'calendar2-week-fill' |
'reply-all' |
'qr-code' |
'sort-numeric-down-alt' |
'credit-card-2-back-fill' |
'chevron-compact-left' |
'cloud-rain-fill' |
'globe2' |
'envelope-open-fill' |
'balloon-heart-fill' |
'phone' |
'grid-1x2-fill' |
'clipboard2-check-fill' |
'cloud-sleet-fill' |
'calendar3-week-fill' |
'layout-text-window' |
'arrow-up-left-square-fill' |
'volume-off-fill' |
'tag-fill' |
'square' |
'badge-tm' |
'cloud-sun' |
'safe-fill' |
'filetype-sass' |
'people' |
'badge-sd-fill' |
'phone-vibrate' |
'arrows-move' |
'distribute-horizontal' |
'telephone-minus-fill' |
'caret-up' |
'play-btn' |
'arrow-down-right-circle-fill' |
'hr' |
'chevron-double-left' |
'magic' |
'pinterest' |
'shop-window' |
'file-diff-fill' |
'currency-euro' |
'webcam' |
'border-all' |
'calendar-date-fill' |
'check' |
'type-h1' |
'file-zip' |
'modem' |
'file-earmark-font' |
'sliders' |
'chevron-down' |
'door-closed-fill' |
'diagram-2' |
'calendar-minus-fill' |
'skip-backward-btn-fill' |
'dice-5' |
'symmetry-vertical' |
'textarea' |
'arrow-up-circle-fill' |
'file-fill' |
'check-all' |
'alarm' |
'telephone-plus-fill' |
'tag' |
'cart-check' |
'filetype-mdx' |
'file-ppt-fill' |
'moisture' |
'key-fill' |
'folder-fill' |
'diamond-fill' |
'chat-right-fill' |
'badge-sd' |
'chat-left-fill' |
'heptagon' |
'displayport' |
'currency-bitcoin' |
'cart4' |
'filetype-docx' |
'signal' |
'journal-x' |
'arrow-counterclockwise' |
'palette2' |
'save2' |
'file-excel-fill' |
'stop-btn' |
'bag-plus' |
'chat-square' |
'filter-square' |
'shift' |
'truck-flatbed' |
'safe2-fill' |
'sort-down-alt' |
'ticket-detailed-fill' |
'type' |
'layers-fill' |
'wrench-adjustable' |
'file-earmark-person' |
'plus-circle' |
'cloud-minus-fill' |
'emoji-smile-upside-down-fill' |
'arrow-down-square-fill' |
'arrow-down-short' |
'question-diamond-fill' |
'bookmark-check-fill' |
'person-x-fill' |
'lamp' |
'exclude' |
'twitch' |
'megaphone-fill' |
'phone-landscape' |
'tablet' |
'record-fill' |
'file-earmark-play' |
'clipboard-heart-fill' |
'save' |
'cloud-sun-fill' |
'file-earmark-bar-graph' |
'chat-quote-fill' |
'file-earmark-ppt-fill' |
'dash-square' |
'cart-check-fill' |
'calendar2-event' |
'screwdriver' |
'heptagon-half' |
'filetype-csv' |
'stack-overflow' |
'inbox' |
'person-video3' |
'braces-asterisk' |
'journal-bookmark-fill' |
'paint-bucket' |
'skip-start' |
'cloud-rain-heavy-fill' |
'arrow-bar-left' |
'calendar2-plus-fill' |
'battery-half' |
'rss' |
'emoji-expressionless' |
'emoji-laughing-fill' |
'bootstrap-fill' |
'incognito' |
'basket' |
'skip-end-circle' |
'twitter' |
'filter-square-fill' |
'text-paragraph' |
'emoji-wink' |
'badge-cc' |
'file-earmark-lock-fill' |
'chat-dots-fill' |
'book' |
'scissors' |
'bookmark-dash' |
'zoom-out' |
'border-style' |
'postcard-heart' |
'file-earmark-break' |
'search' |
'mouse2' |
'chat-square-fill' |
'box2-heart-fill' |
'cart-plus' |
'plus-square-dotted' |
'usb-drive-fill' |
'capslock-fill' |
'link' |
'playstation' |
'dash' |
'camera2' |
'list-task' |
'exclamation-octagon' |
'envelope-slash-fill' |
'clipboard-x-fill' |
'filetype-java' |
'tablet-landscape' |
'cloud-fill' |
'cloud-upload' |
'badge-vo' |
'menu-button-wide' |
'pen' |
'caret-right' |
'telephone-outbound-fill' |
'basket-fill' |
'signpost' |
'signpost-fill' |
'file-font' |
'question-square-fill' |
'vinyl' |
'sd-card-fill' |
'exclamation-octagon-fill' |
'patch-exclamation' |
'layout-text-window-reverse' |
'cloud-upload-fill' |
'memory' |
'check-circle' |
'file-medical-fill' |
'arrows-angle-expand' |
'arrow-left-square-fill' |
'eraser' |
'chat-right-heart-fill' |
'file-image-fill' |
'device-hdd' |
'valentine2' |
'envelope-paper-fill' |
'stop-circle' |
'book-half' |
'bag-heart' |
'nintendo-switch' |
'hearts' |
'file-break' |
'postcard' |
'sort-alpha-down' |
'circle-square' |
'box2' |
'list-columns' |
'skip-end-fill' |
'clipboard2-check' |
'calendar-range-fill' |
'exclamation-lg' |
'chevron-compact-up' |
'file-excel' |
'instagram' |
'chat-quote' |
'filetype-html' |
'folder-symlink-fill' |
'handbag-fill' |
'file-easel' |
'box-arrow-in-up-right' |
'sim' |
'folder-plus' |
'arrow-up-right-square' |
'calendar-fill' |
'justify-right' |
'device-hdd-fill' |
'layer-backward' |
'mortarboard' |
'journal-check' |
'sunrise-fill' |
'share' |
'cursor-text' |
'emoji-angry' |
'type-strikethrough' |
'option' |
'device-ssd-fill' |
'file-binary' |
'clipboard2-pulse-fill' |
'journal-arrow-up' |
'shield-slash' |
'person-check-fill' |
'arrow-90deg-down' |
'usb-plug-fill' |
'router' |
'columns-gap' |
'file-earmark-music-fill' |
'speedometer' |
'skip-backward-fill' |
'envelope-x' |
'window-fullscreen' |
'justify-left' |
'bucket' |
'flag-fill' |
'chevron-expand' |
'steam' |
'credit-card-2-back' |
'skip-forward-btn-fill' |
'triangle-half' |
'telephone-outbound' |
'vinyl-fill' |
'dice-2-fill' |
'gift-fill' |
'router-fill' |
'folder2' |
'shield-check' |
'cup' |
'shield-fill' |
'file-earmark-spreadsheet-fill' |
'journal-arrow-down' |
'fonts' |
'badge-4k' |
'cloud-haze2-fill' |
'file-play-fill' |
'clock' |
'gender-ambiguous' |
'file-text-fill' |
'chat-right-quote-fill' |
'exclamation-diamond-fill' |
'file-earmark-break-fill' |
'arrow-up-square' |
'filetype-mp4' |
'rulers' |
'fullscreen-exit' |
'send-exclamation' |
'suit-spade-fill' |
'google' |
'ui-radios-grid' |
'snow3' |
'calendar' |
'journal-text' |
'caret-left-fill' |
'umbrella' |
'sort-numeric-down' |
'dash-circle-fill' |
'lamp-fill' |
'align-bottom' |
'caret-up-square' |
'calendar2-x-fill' |
'cart-plus-fill' |
'telephone-inbound' |
'tv-fill' |
'circle' |
'stoplights-fill' |
'triangle-fill' |
'arrow-up-right-square-fill' |
'file-code' |
'box-arrow-in-right' |
'chevron-bar-up' |
'sort-numeric-up-alt' |
'thermometer-snow' |
'file-earmark-arrow-down-fill' |
'music-player-fill' |
'percent' |
'octagon-half' |
'credit-card-2-front' |
'send-slash' |
'trophy' |
'code-square' |
'terminal' |
'folder' |
'text-left' |
'text-right' |
'envelope-check-fill' |
'badge-vo-fill' |
'geo-fill' |
'circle-half' |
'crop' |
'filter-circle' |
'shield-lock-fill' |
'calendar2-month' |
'thunderbolt' |
'usb-mini-fill' |
'file-zip-fill' |
'link-45deg' |
'stack' |
'calendar4-event' |
'patch-minus-fill' |
'box2-fill' |
'image-alt' |
'zoom-in' |
'arrow-return-left' |
'reception-4' |
'send-check' |
'toggle2-off' |
'cloud-download-fill' |
'dice-1' |
'file-earmark-code-fill' |
'graph-down-arrow' |
'calendar2-date-fill' |
'file-earmark-easel-fill' |
'emoji-kiss-fill' |
'bag' |
'box-arrow-left' |
'bag-x' |
'wind' |
'bandaid' |
'arrow-through-heart-fill' |
'arrow-right-square' |
'menu-button' |
'window-sidebar' |
'credit-card-fill' |
'cloud-drizzle' |
'card-text' |
'file-earmark-plus' |
'calendar2-x' |
'journals' |
'chat-fill' |
'house-fill' |
'grid-3x2-gap' |
'arrow-up-left-circle' |
'cloud-haze2' |
'window-dash' |
'music-note' |
'arrow-down' |
'arrow-up-left' |
'question-square' |
'hdd-network' |
'arrow-repeat' |
'layers-half' |
'layout-text-sidebar-reverse' |
'meta' |
'laptop-fill' |
'mic-mute' |
'calendar3-event' |
'magnet' |
'front' |
'cloud-fog2-fill' |
'grid-3x2' |
'grid-3x2-gap-fill' |
'diamond' |
'clipboard-fill' |
'list-columns-reverse' |
'person-bounding-box' |
'file-earmark-excel-fill' |
'upload' |
'person' |
'arrow-down-right-square-fill' |
'bookmark-x' |
'wrench' |
'terminal-split' |
'signpost-2-fill' |
'square-fill' |
'disc-fill' |
'badge-8k' |
'minecart-loaded' |
'arrow-up-left-square' |
'bar-chart-steps' |
'clipboard-data-fill' |
'music-note-beamed' |
'file-earmark-check-fill' |
'grid-fill' |
'file-person' |
'bootstrap' |
'arrows-angle-contract' |
'basket2' |
'clipboard2-plus' |
'bag-heart-fill' |
'filetype-exe' |
'filetype-xlsx' |
'calendar2-plus' |
'easel3-fill' |
'calendar2-day' |
'stopwatch' |
'ear' |
'unlock' |
'balloon-heart' |
'sticky-fill' |
'cash' |
'brightness-alt-high-fill' |
'basket2-fill' |
'volume-up-fill' |
'arrow-90deg-right' |
'calendar2' |
'filter-left' |
'cash-stack' |
'magnet-fill' |
'envelope' |
'hand-index' |
'dice-2' |
'type-h3' |
'dice-4' |
'aspect-ratio-fill' |
'three-dots-vertical' |
'bicycle' |
'folder-x' |
'envelope-open-heart-fill' |
'caret-right-fill' |
'pip' |
'badge-cc-fill' |
'recycle' |
'bar-chart-fill' |
'watch' |
'hourglass' |
'file-music' |
'quora' |
'check2-square' |
'sim-fill' |
'clipboard2-fill' |
'file-earmark-post' |
'trash3-fill' |
'mouse2-fill' |
'emoji-frown-fill' |
'robot' |
'graph-up-arrow' |
'bookmark-x-fill' |
'mouse3' |
'badge-vr-fill' |
'layout-sidebar' |
'pin' |
'patch-exclamation-fill' |
'cloud-plus' |
'skip-forward-circle' |
'chat-right-heart' |
'puzzle' |
'cloud-snow' |
'file-plus' |
'asterisk' |
'bookmark-heart' |
'file-earmark-richtext' |
'cloud-rain-heavy' |
'shield-fill-exclamation' |
'textarea-t' |
'printer' |
'box-arrow-in-down-right' |
'camera-video-fill' |
'input-cursor-text' |
'file-arrow-down' |
'bank' |
'yin-yang' |
'headset' |
'chat-right-dots' |
'bug' |
'speedometer2' |
'dice-3-fill' |
'image' |
'file-earmark-slides' |
'border-outer' |
'telegram' |
'cloudy' |
'suit-club-fill' |
'share-fill' |
'blockquote-left' |
'mask' |
'badge-ar-fill' |
'piggy-bank' |
'cursor-fill' |
'calendar-plus' |
'type-italic' |
'file-earmark-play-fill' |
'hand-thumbs-down' |
'send-x' |
'question-circle' |
'hourglass-bottom' |
'x-octagon' |
'question-circle-fill' |
'envelope-open' |
'x-square' |
'file-earmark-easel' |
'chat' |
'keyboard' |
'arrow-up' |
'gear-wide' |
'caret-down-fill' |
'dpad' |
'cart' |
'briefcase' |
'plus-slash-minus' |
'filter' |
'whatsapp' |
'exclamation-circle' |
'person-video2' |
'egg' |
'dice-6-fill' |
'calendar2-month-fill' |
'cloud-minus' |
'telephone-forward' |
'calendar3-fill' |
'chevron-bar-left' |
'newspaper' |
'layers' |
'badge-wc' |
'check2' |
'person-video' |
'calendar2-event-fill' |
'blockquote-right' |
'file-easel-fill' |
'usb-micro-fill' |
'caret-up-square-fill' |
'disc' |
'file-earmark-word-fill' |
'pen-fill' |
'upc-scan' |
'lock' |
'caret-left-square' |
'cloud-arrow-down' |
'file-play' |
'github' |
'translate' |
'cloud-snow-fill' |
'usb-plug' |
'moon' |
'plus-circle-dotted' |
'signpost-split' |
'star-half' |
'arrow-down-left-circle' |
'geo' |
'toggles2' |
'file-earmark-lock' |
'filetype-woff' |
'cloud' |
'handbag' |
'body-text' |
'chevron-up' |
'snow' |
'grid-3x3-gap-fill' |
'person-check' |
'stop-btn-fill' |
'file-earmark-richtext-fill' |
'camera-reels-fill' |
'file-earmark-post-fill' |
'clipboard' |
'filetype-cs' |
'gpu-card' |
'list-check' |
'pc' |
'caret-down-square-fill' |
'brush' |
'arrow-up-square-fill' |
'motherboard-fill' |
'person-square' |
'file-x' |
'chat-left-dots-fill' |
'ladder' |
'telephone' |
'sunglasses' |
'spellcheck' |
'filetype-svg' |
'file-richtext-fill' |
'emoji-kiss' |
'cloudy-fill' |
'file-plus-fill' |
'box-arrow-in-up-left' |
'chat-square-quote' |
'calendar-range' |
'code' |
'question-octagon-fill' |
'calendar3' |
'water' |
'projector-fill' |
'filetype-ttf' |
'phone-fill' |
'aspect-ratio' |
'wifi' |
'cloud-hail' |
'play-circle' |
'three-dots' |
'music-player' |
'arrow-left-right' |
'cone' |
'box-arrow-in-down-left' |
'lightning-charge-fill' |
'flower1' |
'filetype-wav' |
'stoplights' |
'battery' |
'pentagon-half' |
'vector-pen' |
'border' |
'egg-fried' |
'box-arrow-right' |
'badge-hd' |
'sliders2-vertical' |
'clipboard-check' |
'bookmark-plus' |
'optical-audio' |
'thunderbolt-fill' |
'cloud-lightning' |
'record2' |
'layout-text-sidebar' |
'file-earmark-text' |
'file-lock' |
'wifi-off' |
'fullscreen' |
'thermometer' |
'window-plus' |
'calendar2-range-fill' |
'calendar2-day-fill' |
'pause-btn-fill' |
'envelope-paper-heart' |
'hand-index-thumb-fill' |
'hand-thumbs-up-fill' |
'skip-end-circle-fill' |
'mouse-fill' |
'menu-app-fill' |
'caret-left' |
'folder2-open' |
'tablet-fill'
